<header class="wrap-section__header">
<figure class="wrap-section__header__teamlogo"><img src="/res/images/team-logo/MmmU7K6n-b92lfEJC.png" alt="Brighton &amp; Hove Albion Football Club">
</figure>
<h1 class="wrap-section__header__title">Brighton &amp; Hove Albion Football Club (England)</h1>
</header>